//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFF_2017_Dossier_3.HumanCoServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HumanCoServiceReference.HumanCoWebServiceSoap")]
    public interface HumanCoWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/NombreParticipantsCampagne", ReplyAction="*")]
        int NombreParticipantsCampagne(int idCamp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HumanCoWebServiceSoapChannel : EFF_2017_Dossier_3.HumanCoServiceReference.HumanCoWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HumanCoWebServiceSoapClient : System.ServiceModel.ClientBase<EFF_2017_Dossier_3.HumanCoServiceReference.HumanCoWebServiceSoap>, EFF_2017_Dossier_3.HumanCoServiceReference.HumanCoWebServiceSoap {
        
        public HumanCoWebServiceSoapClient() {
        }
        
        public HumanCoWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HumanCoWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HumanCoWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HumanCoWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int NombreParticipantsCampagne(int idCamp) {
            return base.Channel.NombreParticipantsCampagne(idCamp);
        }
    }
}
